#
# 	Main Makefile for the dmod project. You can include this file in your project Makefile
#
DMOD_DIR=../..

# -----------------------------------------------------------------------------
#   Subdirectories
# -----------------------------------------------------------------------------
SUBDIRS = dmod_manifest dmod_dependencies
SYSTEM_SUBDIRS = 
MODULE_SUBDIRS = 

# -----------------------------------------------------------------------------
# 	Initialization of paths
# -----------------------------------------------------------------------------
include $(DMOD_DIR)/paths.mk
include $(DMOD_SUBDIRS_FILE_PATH)