definitions:
  caches:
    build: build

image: chocotechnologies/dmod:1.0.0

pipelines:
  default:
    - step:
        name: 'CMAKE: Build system mode for x86_64'
        caches:
          - build
        artifacts:
          - ./build/examples/system/dmod_loader
        script:
          - rm -rf build
          - mkdir -p build 
          - cd build
          - cmake .. -DDMOD_MODE=DMOD_SYSTEM
          - cmake --build .
    - step:
        name: 'CMAKE: Build module mode for x86_64'
        caches:
          - build
        artifacts:
          - build/dmf/example_app.dmf
          - build/dmf/example_lib.dmf
        script:
          - mkdir -p build 
          - cd build
          - cmake .. -DDMOD_MODE=DMOD_MODULE
          - cmake --build .
    - step:
        name: 'CMAKE: Run the example app'
        caches:
          - build 
        script:
          - ls -la build/examples/system
          - ls -la build/dmf
          - ./build/examples/system/dmod_loader ./build/dmf/example_app.dmf
    - step:
        name: 'MAKE: Build system mode for x86_64'
        artifacts:
          - ./build/examples/system/dmod_loader
        script:
          - rm -rf build
          - make DMOD_MODE=DMOD_SYSTEM
    - step:
        name: 'MAKE: Build module mode for x86_64'
        script:
          - make DMOD_MODE=DMOD_MODULE
    - step:
        name: 'MAKE: Run the example app'
        artifacts:
          - build/dmf/example_app.dmf
          - build/dmf/example_lib.dmf
        caches:
          - build 
        script:
          - ls -la build/examples/system
          - ls -la build/dmf
          - ./build/examples/system/dmod_loader build/dmf/example_app.dmf