definitions:
  caches:
    build: build

image: chocotechnologies/dmod:1.0.0

pipelines:
  default:
    - step:
        name: 'CMAKE: Build for x86_64'
        script:
          - rm -rf build
          - mkdir -p build 
          - cd build
          - cmake .. -DDMOD_MODE=DMOD_MODULE
          - cmake --build .
          - cmake .. -DDMOD_MODE=DMOD_SYSTEM
          - cmake --build .
          - ./examples/system/dmod_loader ./dmf/example_app.dmf
    - step:
        name: 'MAKE: Build for x86_64'
        artifacts:
          - ./build/examples/system/dmod_loader
          - ./build/dmf/example_app.dmf
          - ./build/dmf/dmodex.dmf
        script:
          - rm -rf build
          - make DMOD_MODE=DMOD_SYSTEM
          - make DMOD_MODE=DMOD_MODULE
          - ./build/examples/system/dmod_loader build/dmf/example_app.dmf