ifndef DMOD_USE_STDLIB
    DMOD_USE_STDLIB = ON
endif
ifndef DMOD_USE_GETENV
    DMOD_USE_GETENV = ON
endif

ifndef DMOD_USE_STDIO
    DMOD_USE_STDIO = ON
endif

ifndef DMOD_USE_ASSERT
    DMOD_USE_ASSERT = ON
endif

ifndef DMOD_USE_PTHREAD
    DMOD_USE_PTHREAD = ON
endif

ifndef DMOD_USE_MMAN
    DMOD_USE_MMAN = ON
endif

ifndef DMOD_USE_ALIGNED_ALLOC
    DMOD_USE_ALIGNED_ALLOC = ON
endif
ifndef DMOD_USE_ALIGNED_MALLOC_MOCK
    ifneq ($(DMOD_USE_ALIGNED_ALLOC), ON)
        DMOD_USE_ALIGNED_MALLOC_MOCK=ON
    else
        DMOD_USE_ALIGNED_MALLOC_MOCK=OFF
    endif
endif

ifndef DMOD_USE_REALLOC
    DMOD_USE_REALLOC = ON
endif

ifndef DMOD_USE_FASTLZ
    DMOD_USE_FASTLZ = ON
endif

ifndef DMOD_MAX_MODULES
    DMOD_MAX_MODULES = 30
endif

ifndef DMOD_MAX_REQUIRED_MODULES
    DMOD_MAX_REQUIRED_MODULES = 10
endif

ifndef DMOD_MODE
    DMOD_MODE = DMOD_SYSTEM
endif

ifndef DMOD_SYSTEM_VERSION_MAJOR
    DMOD_SYSTEM_VERSION_MAJOR = 0
endif

ifndef DMOD_SYSTEM_VERSION_MINOR
    DMOD_SYSTEM_VERSION_MINOR = 1
endif

ifndef DMOD_BUILD_TESTS
    DMOD_BUILD_TESTS = ON
endif

ifndef DMOD_BUILD_EXAMPLES
    DMOD_BUILD_EXAMPLES = ON
endif

ifndef DMOD_BUILD_TOOLS
    DMOD_BUILD_TOOLS = ON
endif
