# #############################################################################
# 
# 	Example application module that exercises DMOD_LOG_STEP_* macros.
#
# #############################################################################
DMOD_DIR=../../..

# -----------------------------------------------------------------------------
#  Paths initialization
# -----------------------------------------------------------------------------
include $(DMOD_DIR)/paths.mk

# -----------------------------------------------------------------------------
#   Module configuration
# -----------------------------------------------------------------------------
DMOD_MODULE_NAME=log_step
DMOD_MODULE_VERSION=0.1
DMOD_AUTHOR_NAME=Patryk Kubiak
DMOD_CSOURCES=main.c
DMOD_CXXSOURCES=
DMOD_INC_DIRS=
DMOD_LIBS=
DMOD_DEFINITIONS=

# -----------------------------------------------------------------------------
#   Include the dmod app makefile
# -----------------------------------------------------------------------------
include $(DMOD_DMF_APP_FILE_PATH)
