FROM ubuntu:20.04

ENV DEBIAN_FRONTEND=noninteractive

# This line installs wget tool - you don't need to use it if you already have it
RUN apt-get update && apt-get install -y wget gcc g++ make git jq zip unzip libcurl4-openssl-dev gcovr openocd libusb-1.0-0 ca-certificates xz-utils python3 python3-pip python3-venv ninja-build

# This downloads an installation script and run it 
RUN wget -O - https://raw.githubusercontent.com/JohnAmadis/choco-scripts/refs/heads/master/install-choco-scripts.sh | bash

# Creates directory for the tools
ENV TOOLS_DIR=/tools
RUN mkdir $TOOLS_DIR

# Moves a arm-none-eabi package into the image
ENV ARM_NONE_EABI_VERSION=13.3.rel1
ENV ARM_NONE_EABI_DIR_NAME=arm-gnu-toolchain
ENV ARM_NONE_EABI_FILE_NAME=$ARM_NONE_EABI_DIR_NAME-$ARM_NONE_EABI_VERSION-x86_64-arm-none-eabi.tar.xz
ENV ARM_NONE_EABI_EXTRACTED_DIR_NAME=$ARM_NONE_EABI_DIR_NAME-$ARM_NONE_EABI_VERSION-x86_64-arm-none-eabi
ENV ARM_NONE_EABI_FILE_PATH=$TOOLS_DIR/$ARM_NONE_EABI_FILE_NAME
WORKDIR $TOOLS_DIR
RUN wget https://developer.arm.com/-/media/Files/downloads/gnu/$ARM_NONE_EABI_VERSION/binrel/$ARM_NONE_EABI_FILE_NAME

# Installs arm-none-eabi tools (version currently it is 10.3)
WORKDIR /tools
RUN tar xf $ARM_NONE_EABI_FILE_PATH
RUN rm -f $ARM_NONE_EABI_FILE_PATH
# Removing of version suffix
ENV ARM_NONE_EABI_DIR_PATH=$TOOLS_DIR/$ARM_NONE_EABI_DIR_NAME
RUN mv $TOOLS_DIR/$ARM_NONE_EABI_EXTRACTED_DIR_NAME $ARM_NONE_EABI_DIR_PATH
ENV ARM_NONE_EABI_BIN_DIR_PATH=$ARM_NONE_EABI_DIR_PATH/bin
ENV PATH=$PATH:$ARM_NONE_EABI_BIN_DIR_PATH

# Moves an Xtensa toolchain package into the image (used for ESP32-S3 / T-Deck Pro)
ENV XTENSA_ESP_VERSION=14.2.0_20260121
ENV XTENSA_ESP_DIR_NAME=xtensa-esp-elf
ENV XTENSA_ESP_FILE_NAME=$XTENSA_ESP_DIR_NAME-$XTENSA_ESP_VERSION-x86_64-linux-gnu.tar.xz
ENV XTENSA_ESP_FILE_PATH=$TOOLS_DIR/$XTENSA_ESP_FILE_NAME
WORKDIR /tools
RUN wget https://github.com/espressif/crosstool-NG/releases/download/esp-$XTENSA_ESP_VERSION/$XTENSA_ESP_FILE_NAME

# Installs Xtensa tools (ESP toolchain; includes xtensa-esp32s3-elf-* binaries natively)
WORKDIR /tools
RUN tar xf $XTENSA_ESP_FILE_PATH
RUN rm -f $XTENSA_ESP_FILE_PATH
ENV XTENSA_ESP_DIR_PATH=$TOOLS_DIR/$XTENSA_ESP_DIR_NAME
RUN XTENSA_ESP_SRC_DIR="$(find $TOOLS_DIR -maxdepth 1 -mindepth 1 -type d \( -name 'xtensa-esp-elf*' -o -name 'xtensa-esp32*' \) | head -n 1)" && \
	test -n "$XTENSA_ESP_SRC_DIR" && \
	if [ "$XTENSA_ESP_SRC_DIR" != "$XTENSA_ESP_DIR_PATH" ]; then mv "$XTENSA_ESP_SRC_DIR" "$XTENSA_ESP_DIR_PATH"; fi
ENV XTENSA_ESP_BIN_DIR_PATH=$XTENSA_ESP_DIR_PATH/bin
ENV PATH=$PATH:$XTENSA_ESP_BIN_DIR_PATH

# Installs ESP-IDF
ENV ESP_IDF_VERSION=v5.2.2
ENV IDF_TOOLS_PATH=/tools/.espressif
ENV IDF_PATH=/tools/esp-idf
WORKDIR /tools
RUN git clone --recursive --branch $ESP_IDF_VERSION https://github.com/espressif/esp-idf.git $IDF_PATH
RUN $IDF_PATH/install.sh esp32s3
RUN echo '. $IDF_PATH/export.sh >/dev/null 2>&1' >> /etc/bash.bashrc

# Installs cmake from the repository
ENV CMAKE_VERSION=3.31.3
ENV CMAKE_URL=https://github.com/Kitware/CMake/releases/download/v$CMAKE_VERSION/cmake-$CMAKE_VERSION-linux-x86_64.sh
RUN wget $CMAKE_URL -O /tmp/cmake.sh
RUN chmod +x /tmp/cmake.sh
RUN /tmp/cmake.sh --skip-license --prefix=/usr

WORKDIR /
