# CMake generated Testfile for 
# Source directory: /home/runner/work/dmod/dmod/tests
# Build directory: /home/runner/work/dmod/dmod/build2/tests
# 
# This file includes the relevant testing commands required for 
# testing this directory and lists subdirectories to be tested as well.
add_test(tests_dmod_ctx "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_ctx")
set_tests_properties(tests_dmod_ctx PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_hlp "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_hlp")
set_tests_properties(tests_dmod_hlp PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_ldr "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_ldr")
set_tests_properties(tests_dmod_ldr PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_mgr "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_mgr")
set_tests_properties(tests_dmod_mgr PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_dmfc_api "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_dmfc_api")
set_tests_properties(tests_dmod_dmfc_api PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_getname "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_getname")
set_tests_properties(tests_dmod_getname PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_arch "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_arch")
set_tests_properties(tests_dmod_arch PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_findmatch "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_findmatch")
set_tests_properties(tests_dmod_findmatch PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_readnextmodule "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_readnextmodule")
set_tests_properties(tests_dmod_readnextmodule PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_loadfile_package_path "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_loadfile_package_path")
set_tests_properties(tests_dmod_loadfile_package_path PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_irq "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_irq")
set_tests_properties(tests_dmod_irq PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_rawmem "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_rawmem")
set_tests_properties(tests_dmod_rawmem PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_mock_memory "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_mock_memory")
set_tests_properties(tests_dmod_mock_memory PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_dir "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_dir")
set_tests_properties(tests_dmod_dir PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_snprintf "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_snprintf")
set_tests_properties(tests_dmod_snprintf PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_env "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_env")
set_tests_properties(tests_dmod_env PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_file_readline "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_file_readline")
set_tests_properties(tests_dmod_file_readline PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_cwd "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_cwd")
set_tests_properties(tests_dmod_cwd PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_rename "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_rename")
set_tests_properties(tests_dmod_rename PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_file_remove "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_file_remove")
set_tests_properties(tests_dmod_file_remove PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_stack "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_stack")
set_tests_properties(tests_dmod_stack PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_uptime "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_uptime")
set_tests_properties(tests_dmod_uptime PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_module_log_level "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_module_log_level")
set_tests_properties(tests_dmod_module_log_level PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_version "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_version")
set_tests_properties(tests_dmod_version PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_manifest "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_manifest")
set_tests_properties(tests_dmod_manifest PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_dependencies "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_dependencies")
set_tests_properties(tests_dmod_dependencies PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
add_test(tests_dmod_resource "/home/runner/work/dmod/dmod/build2/tests/tests_dmod_resource")
set_tests_properties(tests_dmod_resource PROPERTIES  _BACKTRACE_TRIPLES "/home/runner/work/dmod/dmod/tests/CMakeLists.txt;41;add_test;/home/runner/work/dmod/dmod/tests/CMakeLists.txt;0;")
subdirs("../_deps/googletest-build")
subdirs("mocks")
subdirs("common")
subdirs("module")
subdirs("system")
subdirs("lib")
