# Path to dmod repository
DMOD_DIR = @DMOD_DIR@

# Module configuration
DMOD_MODULE_NAME = external_test_make
DMOD_MODULE_VERSION = 1.0
DMOD_AUTHOR_NAME = CI Test

# Source files
DMOD_CSOURCES = external_test.c

# Include dmod paths
include $(DMOD_DIR)/paths.mk

# Include dmod app makefile
include $(DMOD_DMF_APP_FILE_PATH)
