#ifndef INC_DMOD_DEFS_H_
#define INC_DMOD_DEFS_H_

#define DMOD_MAX_MODULE_NAME_LENGTH		32

#define DMOD_SIGNATURE_PREFIX		"\021DMOD\022"
#define DMOD_SIGNATURE_SUFFIX		"\022\023"
#define DMOD_MAKE_SIGNATURE( RET, NAME, VERSION, PARAMS )		DMOD_SIGNATURE_PREFIX #RET " " #NAME "@" #VERSION " " #PARAMS DMOD_SIGNATURE_SUFFIX

#endif /* INC_DMOD_DEFS_H_ */
