#ifndef INC_DMOD_DEFS_H_
#define INC_DMOD_DEFS_H_

#define DMOD_HEADER_SIGNATURE           0x444D4F44
#define DMOD_MAX_ARCH_NAME_LENGTH       10
#define DMOD_MAX_MODULE_NAME_LENGTH		32

#define DMOD_SIGNATURE_PREFIX		"\021DMOD\022"
#define DMOD_SIGNATURE_SUFFIX		"\022\023"
#define DMOD_MAKE_SIGNATURE( MODULE, VERSION, RET, NAME, PARAMS )		DMOD_SIGNATURE_PREFIX #NAME "@" #MODULE ":" #VERSION DMOD_SIGNATURE_SUFFIX

#define DMOD_WEAK_SYMBOL		__attribute__((weak))

#endif /* INC_DMOD_DEFS_H_ */
