cmake_minimum_required(VERSION 3.18)
find_package(dmod CONFIG REQUIRED)
project(sdk_assets LANGUAGES C CXX)
if(OLD_ASSET_NAME)
    set(DMOD_FIXTURES_PATHS "${CMAKE_CURRENT_SOURCE_DIR}/fixtures")
else()
    set(DMOD_ASSETS_PATHS "${CMAKE_CURRENT_SOURCE_DIR}/fixtures")
endif()
set(DMOD_DMR_PATH "${CMAKE_CURRENT_SOURCE_DIR}/assets.dmr")
dmod_add_executable(sdk_assets "0.1" main.c)
