#
# This is a makefile for the system tools
#

# -----------------------------------------------------------------------------
# 	Paths configuration
# -----------------------------------------------------------------------------
DMOD_DIR=../../..
THIS_DIR=$(shell pwd)
TOOL_SRC_DIR=$(THIS_DIR)

# -----------------------------------------------------------------------------
# 	Project's definitions
# -----------------------------------------------------------------------------
PROJECT_NAME    = mkdmrpkg
DMOD_SOURCES	= main.c
DMOD_INC_DIRS 	= $(DMOD_DIR)/tools/lib/dmod_resource
DMOD_LIBS 	  	= dmod_resource
DEFINITIONS 	= 

# -----------------------------------------------------------------------------
# 	Initialization of paths
# -----------------------------------------------------------------------------
include $(DMOD_DIR)/paths.mk
include $(DMOD_SYSTEM_TOOL_MK_FILE_PATH)
