#
# 	Main Makefile for the dmod project. You can include this file in your project Makefile
#
DMOD_DIR=..

# -----------------------------------------------------------------------------
#   Subdirectories
# -----------------------------------------------------------------------------
SUBDIRS = lib
SYSTEM_SUBDIRS = system 
MODULE_SUBDIRS = module

# -----------------------------------------------------------------------------
# 	Initialization of paths
# -----------------------------------------------------------------------------
include $(DMOD_DIR)/paths.mk
include $(DMOD_SUBDIRS_FILE_PATH)