# Use the same profiles as the source/FetchContent build, without modifying them.
set(_dmod_profile "")
if(DEFINED DMOD_TOOLS AND NOT DMOD_TOOLS STREQUAL "")
    get_filename_component(_dmod_profile "${DMOD_TOOLS}" ABSOLUTE BASE_DIR "${CMAKE_SOURCE_DIR}")
elseif(DEFINED DMOD_TOOLS_NAME AND NOT DMOD_TOOLS_NAME STREQUAL "")
    set(_dmod_profile "${DMOD_CONFIGS_DIR}/${DMOD_TOOLS_NAME}/tools-cfg.cmake")
endif()

if(NOT _dmod_profile STREQUAL "")
    if(NOT EXISTS "${_dmod_profile}")
        message(FATAL_ERROR "DMOD tools configuration does not exist: ${_dmod_profile}")
    endif()
    get_property(_dmod_loaded_profile GLOBAL PROPERTY DMOD_SDK_LOADED_PROFILE)
    if(_dmod_loaded_profile AND NOT _dmod_loaded_profile STREQUAL _dmod_profile)
        message(FATAL_ERROR "All modules in a build must use the same DMOD tools configuration")
    endif()
    if(NOT _dmod_loaded_profile)
        if(CMAKE_C_COMPILER_LOADED OR CMAKE_CXX_COMPILER_LOADED)
            message(FATAL_ERROR
                "DMOD_TOOLS_NAME/DMOD_TOOLS selects the compiler. Move find_package(dmod CONFIG REQUIRED) before project(), as with the source build's FetchContent_MakeAvailable(dmod).")
        endif()
        if(DEFINED DMOD_SDK_CONFIGURED_PROFILE AND NOT DMOD_SDK_CONFIGURED_PROFILE STREQUAL _dmod_profile)
            message(FATAL_ERROR "Changing DMOD tools configuration requires a fresh build directory")
        endif()
        set(DMOD_SDK_CONFIGURED_PROFILE "${_dmod_profile}" CACHE INTERNAL "SDK tools configuration")
        set(DMOD_TOOLS "${_dmod_profile}")
        include("${DMOD_TOOLS}")
        set_property(GLOBAL PROPERTY DMOD_SDK_LOADED_PROFILE "${_dmod_profile}")
    endif()
endif()
